import Head from 'next/head';
import { useEffect } from 'react';

export default function Home() {
  useEffect(() =>{
    fetchJhon();
    console.log('Hello world');
  }, []);
const fetchJhon = async () => {
  const res = await fetch('/api/hello');
  const data = await res.json();

  console.log(data);
}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-3xl font-bold underline'>Lafointaine Sounds</h1>
      </main>
    </>
  )
}
